export const data = {
  baseClueValue: 200,
  dailyDouble: { col: 3, row: 2 },
  board: [
    {
      category: `MONOGRAM MANIA`,
      clues: [
        `EVOLUTIONARY WAR STARTER:
        CD`,
        `LAWYER & EVOLUTIONARY WAR DEFENDER:
        CD`,
        `A FAMOUS PLAYWRIGHT:
        GBS`,
        `WOMEN'S RIGHTS ACTIVIST:
        SBA`,
        `RETIRED FROM THE SUPREME COURT IN 1932 AT AGE 90:
        OWH (JR.)`,
      ],
    },
    {
      category: `COOKING TERMS`,
      clues: [
        `IN THIS COLORFUL TECHNIQUE, MEAT IS RUBBED WITH CAJUN SPICES & COOKED AT HIGH HEAT UNTIL CHARRED, GIVING IT A CRISPY CRUST`,
        `THIS TERM REFERS TO MAKING SUGAR BROWN BY HEATING IN A SKILLET OVER LOW HEAT UNTIL MELTED & GOLDEN`,
        `THIS THIN COTTON CLOTH IS USED TO STRAIN LIQUIDS & BUNDLE UP HERBS & SPICES THAT CAN BE DROPPED INTO SOUP STOCK`,
        `THIS TERM FOR VEGETABLES CUT INTO LONG, THIN STRIPS TO ACCOMPANY A SALAD COMES FROM A FRENCH FIRST NAME`,
        `TO DO THIS TO HERRING OR SALMON, YOU MUST SPLIT, SALT & SMOKE IT`,
      ],
    },
    {
      category: `HISTORY`,
      clues: [
        `I BELIEVE WE'RE ALL IN ACCORD THAT THE LEAGUE OF NATIONS ASSEMBLY MET FOR THE FIRST TIME IN 1920 IN THIS SWISS CITY`,
        `THIS DOCUMENT THAT SAID THE KING WAS SUBJECT TO THE RULE OF LAW WAS REISSUED WITH SOME CHANGES IN 1216, '17 & '25`,
        `IN 1984 THIS MINNESOTAN GOT THE FEWEST ELECTORAL VOTES, 13, OF ANY DEMOCRAT SINCE 1872`,
        `THIS SIBERIAN MYSTIC DIDN'T MAKE IT TO NEW YEAR'S 1917, GETTING POISONED, SHOT TWICE, TIED UP & DROWNED, ALL IN 1 ROUGH DEC. NIGHT`,
        `ON MARCH 13, 1954 50,000 VIETMINH ATTACKED 10,000 FRENCH TROOPS AT A BASE IN THIS VILLAGE`,
      ],
    },
    {
      category: `TV KILLERS`,
      clues: [
        `TERI BAUER DOES NOT LIVE TO SEE ANOTHER DAY ON THIS TV SHOW, KILLED BY HER HUBBY'S DUPLICITOUS COWORKER`,
        `AN EARLY EPISODE OF THIS KILLER CABLE SHOW WAS "SHRINK WRAP"; NEAR THE FINALE CAME "GOODBYE MIAMI"`,
        `ON "THE OFFICE" HE KILLED SPRINKLES, THE CAT OF HIS SOMETIME LOVE INTEREST ANGELA`,
        `AS SERIAL KILLER BILLY FLYNN, TIM CURRY CONFRONTED SHEMAR MOORE ON THIS CBS SHOW`,
        `ON "THE LAST MAN ON EARTH", JANUARY JONES GOT REVENGE OF A SORT, GUNNING DOWN THIS ACTOR IN A CAMEO`,
      ],
    },
    {
      category: `KNOW THE NOSE`,
      clues: [
        `AN EPISTAXIS IS ONE OF THESE, MAYBE AFTER A PUNCH`,
        `THE COLUMELLA OR TIP OF YOUR NOSE IS THE LOWER, FRONT PORTION OF THIS NASAL DIVIDER`,
        `(JIMMY OF THE CLUE CREW SHOWS THE BRAIN ON A MONITOR.) INHALATIONS COME THROUGH THE NOSTRILS AND TRIGGER ODOR SIGNALS THAT ARE RELAYED TO THE BRAIN BY THESE CRANIAL NERVES`,
        `A NOSE JOB IS THE COMMON NAME FOR THIS 11-LETTER MEDICAL PROCEDURE`,
        `IT'S THAT WEIRD DIVOT JUST BELOW THE NOSE & ABOVE THE UPPER LIP`,
      ],
    },
    {
      category: `A LITTLE ENTITLED`,
      clues: [
        `IT'S SAID OF SOME PEOPLE, "BORN ON THIRD BASE & THINKS HE HIT" THIS`,
        `OLIVER GOLDSMITH ONCE NOTED THAT A CERTAIN MAN WAS BORN WITH ONE OF THESE IN HIS MOUTH, ANOTHER WITH A WOODEN LADLE`,
        `THE '70S WERE CALLED THIS 2-LETTER DECADE`,
        `IN 1989 A SYNDROME NAMED FOR THIS TYPE OF CODDLED CHILD WAS IDENTIFIED AS INVOLVING SELF-CENTERED & IMMATURE BEHAVIOR`,
        `DESCRIBING THE IDLE WEALTHY, IN 1899 THORSTEIN VEBLEN WROTE OF THIS "CLASS", NOW A COMMON PHRASE`,
      ],
    },
  ],
};
